// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abvnmircxhoyuiwzella.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFidm5taXJjeGhveXVpd3plbGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzA5NjAsImV4cCI6MjA2NTQ0Njk2MH0.xb0IIi5x_LeLMNJWaq12qibTLqIugLVWihTQX4e8_dw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);